### ISSUE TITLE
Question about ignore threshold?

### ISSUE THREAD

**Issue by LMerCy** [megvii-model/YOLOF#5]
The paper points out the importance of **balance matching** of label assign, but actually in the code you ignores the anchor(pred) whose iou>NEG_IGNORE_THRESHOLD or  < POS_IGNORE_THRESHOLD, which may break the balance?

Also, it seems you ignore the anchor(pred) whose iou > NEG_IGNORE_THRESHOLD  only make sense with max-iou label assign, why you use the the anchor(pred) whose iou is maxium or between NEG_IGNORE_THRESHOLD  and NEG_IGNORE_THRESHOLD ?

https://github.com/megvii-model/YOLOF/blob/86288132be25f0fc54d3c4b35c97a774222c12fc/playground/detection/coco/yolof/yolof_base/yolof.py#L186-L231

**Comment by chensnathan** [comment]
Hi, thanks for your questions.

For your first question, in the paper, we say that we construct `balance on positive anchors`. Thus, setting the threshold for negative anchors does not affect the balance. Add threshold for positive anchors indeed bring risk to ruin the balance on positives. However, we only ignore the unreasonable positive anchors (whose IoU with the gt boxes is lower than 0.15) during training. This ignorance will not affect the distribution of positive anchors too much. We can also achieve our goal that makes gt boxes on various scales participate in training and avoid unreasonable training samples that may hurt the training.

For your second question, I don't fully understand. Here, I provide some explanations on why we set ignore threshold for negatives. In this paper, we obtain positive anchors by choosing gt boxes' k nearest anchors and leave the rest to be negative anchors. However, there may exist negative anchors that have similar distances with the chosen positives. These negatives may cause ambiguity for model training if we just set them as negatives. Given that we want the model's predict boxes on negative anchors to have low IoU with gt boxes, we set a threshold on the IoU between predicted boxes and gt boxes instead of the IoU between anchor boxes and gt boxes. You can check [this line](https://github.com/megvii-model/YOLOF/blob/86288132be25f0fc54d3c4b35c97a774222c12fc/playground/detection/coco/yolof/yolof_base/yolof.py#L171). For ignoring, we first ignore all the indexes whose max IoU with gt boxes are greater than the negative threshold ([Line197](https://github.com/megvii-model/YOLOF/blob/86288132be25f0fc54d3c4b35c97a774222c12fc/playground/detection/coco/yolof/yolof_base/yolof.py#L197)), then for positive, we replace the `gt_classes` on positive indexes with the `target_classes_o` ([Line201](https://github.com/megvii-model/YOLOF/blob/86288132be25f0fc54d3c4b35c97a774222c12fc/playground/detection/coco/yolof/yolof_base/yolof.py#L201)).

Feel free to comment if you have further questions.

**Comment by LMerCy** [comment]
@chensnathan Thanks for your detailed response!  I think i missundertood the ```neg_ignore_thresh``` (0.7) , actually it is used for ignore the ***negative*** anchor instead of ***positive*** anchor. Thanks again for your nice work!
